/**
 * Generate dist/sw.js after the Astro build.
 *
 * Hand-rolled rather than Workbox: the caching rules here are unusual enough
 * that a generic tool would need as much configuration as this file has code,
 * and the one thing that must not go wrong — never precaching the 9.7 MB codec
 * — is easier to guarantee when it is one visible line.
 *
 * Two tiers, and the split is the whole design:
 *
 *   PRECACHE  the shell. Small, fetched on install, so the page renders offline.
 *   RUNTIME   the codecs. Large, cached only once a conversion has actually
 *             pulled one. Precaching these would download 9.7 MB from someone
 *             who came to convert a PNG and will never touch audio.
 */

import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const dist = join(root, "dist");

/**
 * The shell is exactly what the HTML references, and nothing else.
 *
 * Derived from the markup rather than by filtering the whole output directory,
 * because "everything under a size cap" quietly swept in pdf.js and mediabunny
 * — 1.5 MB of engines installed on someone who came to convert a PNG. Engine
 * chunks are loaded on demand by workers, so they never appear in the HTML and
 * are correctly left to the runtime cache.
 */
const html = await readFile(join(dist, "index.html"), "utf8");
// Any attribute value pointing at build output, not just src/href: Astro
// islands name their chunks with `component-url` and `renderer-url`, so a
// src/href-only regex found the CSS and missed React entirely — a 20 KB "shell"
// that could not render.
const referenced = new Set(
  [...html.matchAll(/"(\/(?:_astro|ffmpeg)\/[^"]+\.(?:js|mjs|css))"/g)].map((m) => m[1]),
);

/**
 * Follow each entry chunk's STATIC import graph.
 *
 * The HTML names only the entry points. Loading a module also loads everything
 * it statically imports, and if one of those is missing the whole module fails
 * — reported against the entry chunk, which is why the error says
 * "Failed to fetch dynamically imported module: Converter.js" while
 * Converter.js is sitting in the cache. Dynamic imports are deliberately not
 * followed: those are the engines, and they belong in the runtime cache.
 */
async function staticImportsOf(url, seen = new Set()) {
  if (seen.has(url) || !url.endsWith(".js")) return seen;
  seen.add(url);
  let code;
  try {
    code = await readFile(join(dist, url.slice(1)), "utf8");
  } catch {
    return seen;
  }
  // Rollup emits relative specifiers: import{x}from"./chunk-HASH.js"
  for (const match of code.matchAll(
    /(?:^|[\s;}])(?:import|export)[^"';]*?["'](\.\/[^"']+\.js)["']/g,
  )) {
    const resolved = "/_astro/" + match[1].replace(/^\.\//, "");
    await staticImportsOf(resolved, seen);
  }
  return seen;
}

const graph = new Set();
for (const url of referenced) {
  for (const dep of await staticImportsOf(url)) graph.add(dep);
}

const precache = ["/", "/index.html", "/favicon.svg", ...referenced, ...graph];
let precacheBytes = 0;

for (const url of new Set(precache)) {
  if (url === "/") continue; // an alias for index.html, not a file
  try {
    precacheBytes += (await readFile(join(dist, url.slice(1)))).byteLength;
  } catch {
    // Referenced but absent — the install handler skips it rather than failing.
  }
}

// A backstop, not a rule: if the shell ever balloons, that is a bug worth
// stopping the build over rather than shipping a slow first visit.
const MAX_SHELL_BYTES = 600 * 1024;
if (precacheBytes > MAX_SHELL_BYTES) {
  throw new Error(
    `app shell is ${(precacheBytes / 1024).toFixed(0)} KB, over the ` +
      `${MAX_SHELL_BYTES / 1024} KB budget — something large is being precached ` +
      `that should be loaded on demand.`,
  );
}

// A content hash over the precache list AND its contents, so the service worker
// changes exactly when the shell changes — and therefore updates when it should
// and stays quiet when it shouldn't.
const hash = createHash("sha256");
for (const url of [...new Set(precache)].sort()) {
  hash.update(url);
  if (url === "/") continue;
  try {
    hash.update(await readFile(join(dist, url.slice(1))));
  } catch {
    // Missing files contribute their URL only; still a stable version.
  }
}
const version = hash.digest("hex").slice(0, 12);

const sw = `// Generated by scripts/build-sw.mjs — do not edit.
const VERSION = ${JSON.stringify(version)};
const SHELL = "onhand-shell-" + VERSION;
// Deliberately NOT versioned: codecs are content-hashed by the bundler, so an
// old entry is either still correct or never requested again. Wiping 9.7 MB on
// every deploy would make the "downloaded once" promise a lie.
const RUNTIME = "onhand-runtime";

const PRECACHE = ${JSON.stringify([...new Set(precache)].sort(), null, 2)};

/** Big, immutable, and worth keeping: the codecs. */
function isRuntimeAsset(url) {
  return (
    url.pathname.startsWith("/ffmpeg/") ||
    url.pathname.endsWith(".wasm") ||
    url.pathname.endsWith(".gz")
  );
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(SHELL);
      // Individually, not addAll: addAll rejects the whole install if a single
      // request fails, which turns one 404 into no offline support at all.
      await Promise.all(
        PRECACHE.map(async (url) => {
          try {
            const response = await fetch(url, { cache: "reload" });
            if (response.ok) await cache.put(url, response);
          } catch {
            // Skipped. The runtime handler will pick it up on first use.
          }
        }),
      );
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      for (const key of await caches.keys()) {
        // Drop old shells; never touch the runtime codec cache.
        if (key.startsWith("onhand-shell-") && key !== SHELL) await caches.delete(key);
      }
      await self.clients.claim();
    })(),
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  // Same-origin only. We have no third-party requests, and proxying one through
  // here would be the exact thing this product promises not to do.
  if (url.origin !== self.location.origin) return;

  if (isRuntimeAsset(url)) {
    event.respondWith(cacheFirst(request, RUNTIME));
    return;
  }

  // Content-hashed bundler output goes in the UNVERSIONED cache. The URL
  // changes when the bytes change, so an old entry is never stale — and
  // keeping it there means a deploy does not wipe it. Caching these in the
  // versioned shell (as this did) meant every deploy silently destroyed
  // offline support until the user repeated every conversion.
  if (url.pathname.startsWith("/_astro/")) {
    event.respondWith(cacheFirst(request, RUNTIME));
    return;
  }

  // Documents: network first, so a deploy is picked up immediately, falling
  // back to cache when there is no network. That fallback is the feature.
  if (request.mode === "navigate" || url.pathname.endsWith(".html") || url.pathname === "/") {
    event.respondWith(networkFirst(request));
    return;
  }

  event.respondWith(cacheFirst(request, SHELL));
});

async function cacheFirst(request, cacheName) {
  const cached = await caches.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  // Only cache a real success. Caching an opaque or error response makes the
  // offline badge claim capability the app does not have.
  if (response.ok && response.type === "basic") {
    const cache = await caches.open(cacheName);
    cache.put(request, response.clone());
  }
  return response;
}

async function networkFirst(request) {
  try {
    const response = await fetch(request);
    if (response.ok && response.type === "basic") {
      const cache = await caches.open(SHELL);
      cache.put(request, response.clone());
    }
    return response;
  } catch (err) {
    const cached = (await caches.match(request)) ?? (await caches.match("/"));
    if (cached) return cached;
    throw err;
  }
}

// Lets the page ask what is actually cached rather than guess. The offline
// badge is built on this: it must never claim more than is true.
self.addEventListener("message", (event) => {
  if (event.data?.type !== "cached-assets") return;
  event.waitUntil(
    (async () => {
      // Every cache, not just RUNTIME. Codecs land in both: .wasm files are
      // runtime assets, but libheif and the oxipng glue are .js and go to the
      // shell cache. Asking only RUNTIME made the badge report "not available"
      // for a pair whose codec was sitting in the other cache.
      const urls = [];
      for (const name of await caches.keys()) {
        if (!name.startsWith("onhand-")) continue;
        const cache = await caches.open(name);
        for (const request of await cache.keys()) {
          urls.push(new URL(request.url).pathname);
        }
      }
      // Reply on the transferred port when there is one. Replying only via
      // event.source sends it to the page's global serviceWorker listener
      // instead, so a caller waiting on its MessageChannel waits forever —
      // and because the caller times out and resolves empty, the badge simply
      // never appears rather than erroring. Silent, and therefore worse.
      const message = { type: "cached-assets", urls };
      if (event.ports && event.ports[0]) event.ports[0].postMessage(message);
      else event.source?.postMessage(message);
    })(),
  );
});
`;

await writeFile(join(dist, "sw.js"), sw);
console.log(
  `service worker: ${new Set(precache).size} shell files precached ` +
    `(${(precacheBytes / 1024).toFixed(0)} KB), version ${version}`,
);
